apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
spec:
  type: NodePort
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
